import { Inter } from 'next/font/google';
import './globals.css';
import FooterComponent from '@components/FooterCompanent';
import NavBarComponent from '@components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Clover',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, loading }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-neutral-200`}>
        {loading ? (
          <div className="loader">
            {/* Replace this with your loader component */}
            <center>
              <img src="/img/logo.png" className='w-10 h-10' alt="" />
            </center>
          </div>
        ) : (
          <div>
            <NavBarComponent />
            {children}
            <FooterComponent />
          </div>
        )}
      </body>
    </html>
  );
}
