import { Inter } from "next/font/google";
import "./globals.css";
import FooterComponent from "@components/FooterCompanent";
import NavBarComponent from "@components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Clover",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-neutral-200`}>
        <div>
          <NavBarComponent className="top-2"/>
          {children}
        </div>
        <FooterComponent />
      </body>
    </html>
  );
}
